trade:
  target: 2
  stop: "23:50"
  rest_min: 3
NIFTY:
  base: NIFTY
  option_exchange: NFO
  moneyness: -1       # 0=atm 1=otm -1=itm
  expiry: 20MAR25
  quantity: 75
  target: 5
BANKNIFTY:
  base: BANKNIFTY
  option_exchange: NFO
  moneyness: -1      # 0=atm 1=otm -1=itm
  expiry: 27MAR25
  quantity: 15
  target: 5
log:
  show: 1
  level: 10
